/// Flutter icons AppLogoIcon
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppLogoIcon
///      fonts:
///       - asset: fonts/AppLogoIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppLogoIcon {
  AppLogoIcon._();

  static const _kFontFam = 'AppLogoIcon';

  static const IconData appLogoIcon = IconData(0xe800, fontFamily: _kFontFam);
}
