import 'package:intl/intl.dart';

class Country {
  static const Map<String, String> simpleCurrencySymbols = {
    'AFN': 'Af.',
    'TOP': r'T$',
    'MGA': 'Ar',
    'THB': '\u0e3f',
    'PAB': 'B/.',
    'ETB': 'Birr',
    'VEF': 'Bs',
    'BOB': 'Bs',
    'GHS': 'GH\u20B5',
    'CRC': '\u20a1',
    'NIO': r'C$',
    'GMD': 'GMD',
    'MKD': 'din',
    'BHD': 'din',
    'DZD': 'din',
    'IQD': 'din',
    'JOD': 'din',
    'KWD': 'din',
    'LYD': 'din',
    'RSD': 'din',
    'TND': 'din',
    'AED': 'dh',
    'MAD': 'dh',
    'STD': 'Db',
    'BSD': r'$',
    'FJD': r'$',
    'GYD': r'$',
    'KYD': r'$',
    'LRD': r'$',
    'SBD': r'$',
    'SRD': r'$',
    'AUD': r'$',
    'BBD': r'$',
    'BMD': r'$',
    'BND': r'$',
    'BZD': r'$',
    'CAD': r'$',
    'HKD': r'$',
    'JMD': r'$',
    'NAD': r'$',
    'NZD': r'$',
    'SGD': r'$',
    'TTD': r'$',
    'TWD': r'NT$',
    'USD': r'$',
    'XCD': r'$',
    'VND': '\u20ab',
    'AMD': 'Dram',
    'CVE': r'$',
    'EUR': '\u20ac',
    'AWG': 'Afl.',
    'HUF': 'Ft',
    'BIF': 'FBu',
    'CDF': 'FrCD',
    'CHF': 'CHF',
    'DJF': 'Fdj',
    'GNF': 'FG',
    'RWF': 'RF',
    'XOF': 'CFA',
    'XPF': 'FCFP',
    'KMF': 'CF',
    'XAF': 'FCFA',
    'HTG': 'HTG',
    'PYG': 'Gs',
    'UAH': '\u20b4',
    'PGK': 'PGK',
    'LAK': '\u20ad',
    'CZK': 'K\u010d',
    'SEK': 'kr',
    'ISK': 'kr',
    'DKK': 'kr',
    'NOK': 'kr',
    'HRK': 'kn',
    'MWK': 'MWK',
    'ZMK': 'ZWK',
    'AOA': 'Kz',
    'MMK': 'K',
    'GEL': 'GEL',
    'LVL': 'Ls',
    'ALL': 'Lek',
    'HNL': 'L',
    'SLL': 'SLL',
    'MDL': 'MDL',
    'RON': 'RON',
    'BGN': 'lev',
    'SZL': 'SZL',
    'TRY': '\u20BA',
    'LTL': 'Lt',
    'LSL': 'LSL',
    'AZN': 'man.',
    'BAM': 'KM',
    'MZN': 'MTn',
    'NGN': '\u20a6',
    'ERN': 'Nfk',
    'BTN': 'Nu.',
    'MRO': 'MRO',
    'MOP': 'MOP',
    'CUP': r'$',
    'CUC': r'$',
    'ARS': r'$',
    'CLF': 'UF',
    'CLP': r'$',
    'COP': r'$',
    'DOP': r'$',
    'MXN': r'$',
    'PHP': '\u20b1',
    'UYU': r'$',
    'FKP': '£',
    'GIP': '£',
    'SHP': '£',
    'EGP': 'E£',
    'LBP': 'L£',
    'SDG': 'SDG',
    'SSP': 'SSP',
    'GBP': '£',
    'SYP': '£',
    'BWP': 'P',
    'GTQ': 'Q',
    'ZAR': 'R',
    'BRL': r'R$',
    'OMR': 'Rial',
    'QAR': 'Riyal',
    'YER': 'Rial',
    'IRR': 'Rial',
    'KHR': 'Riel',
    'MYR': 'RM',
    'SAR': 'Riyal',
    'BYR': 'BYR',
    'RUB': '\u20BD',
    'MUR': 'Rs',
    'SCR': 'SCR',
    'LKR': 'Rs',
    'NPR': 'Rs',
    'INR': '\u20b9',
    'PKR': 'Rs',
    'IDR': 'Rp',
    'ILS': '\u20aa',
    'KES': 'Ksh',
    'SOS': 'SOS',
    'TZS': 'TSh',
    'UGX': 'UGX',
    'PEN': 'S/',
    'KGS': 'KGS',
    'UZS': 'so\u02bcm',
    'TJS': 'Som',
    'BDT': '\u09f3',
    'WST': 'WST',
    'KZT': '\u20b8',
    'MNT': '\u20ae',
    'VUV': 'VUV',
    'KPW': '\u20a9',
    'KRW': '\u20a9',
    'JPY': '¥',
    'CNY': '¥',
    'PLN': 'z\u0142',
    'MVR': 'Rf',
    'NLG': 'NAf',
    'ZMW': 'ZK',
    'ANG': 'ƒ',
    'TMT': 'TMT',
  };

  static const Map<String, String> iso3ToCurrency = {
    'AFG': 'AFN',
    'ALB': 'ALL',
    'DZA': 'DZD',
    'ASM': 'USD',
    'AND': 'EUR',
    'AGO': 'AOA',
    'AIA': 'XCD',
    'ATA': 'USD',
    'ATG': 'XCD',
    'ARG': 'ARS',
    'ARM': 'AMD',
    'ABW': 'AWG',
    'AUS': 'AUD',
    'AUT': 'EUR',
    'AZE': 'AZN',
    'BHS': 'BSD',
    'BHR': 'BHD',
    'BGD': 'BDT',
    'BRB': 'BBD',
    'BLR': 'BYN',
    'BEL': 'EUR',
    'BLZ': 'BZD',
    'BEN': 'XOF',
    'BMU': 'BMD',
    'BTN': 'BTN',
    'BOL': 'BOB',
    'BIH': 'BAM',
    'BWA': 'BWP',
    'BVT': 'NOK',
    'BRA': 'BRL',
    'IOT': 'USD',
    'BRN': 'BND',
    'BGR': 'BGN',
    'BFA': 'XOF',
    'BDI': 'BIF',
    'KHM': 'KHR',
    'CMR': 'XAF',
    'CAN': 'CAD',
    'CPV': 'CVE',
    'BES': 'USD',
    'CYM': 'KYD',
    'CAF': 'XAF',
    'TCD': 'XAF',
    'CHL': 'CLP',
    'CHN': 'CNY',
    'CXR': 'AUD',
    'CCK': 'AUD',
    'COL': 'COP',
    'COM': 'KMF',
    'COG': 'XAF',
    'COD': 'CDF',
    'COK': 'NZD',
    'CRI': 'CRC',
    'HRV': 'EUR',
    'CUB': 'CUP',
    'CUW': 'ANG',
    'CYP': 'EUR',
    'CZE': 'CZK',
    'CIV': 'XOF',
    'DNK': 'DKK',
    'DJI': 'DJF',
    'DMA': 'XCD',
    'DOM': 'DOP',
    'ECU': 'USD',
    'EGY': 'EGP',
    'SLV': 'USD',
    'GBR': 'GBP',
    'GNQ': 'XAF',
    'ERI': 'ERN',
    'EST': 'EUR',
    'ETH': 'ETB',
    'FLK': 'FKP',
    'FRO': 'DKK',
    'FJI': 'FJD',
    'FIN': 'EUR',
    'FRA': 'EUR',
    'GUF': 'EUR',
    'PYF': 'XPF',
    'ATF': 'EUR',
    'GAB': 'XAF',
    'GMB': 'GMD',
    'GEO': 'GEL',
    'DEU': 'EUR',
    'GHA': 'GHS',
    'GIB': 'GIP',
    'GRC': 'EUR',
    'GRL': 'DKK',
    'GRD': 'XCD',
    'GLP': 'EUR',
    'GUM': 'USD',
    'GTM': 'GTQ',
    'GGY': 'GBP',
    'GIN': 'GNF',
    'GNB': 'XOF',
    'GUY': 'GYD',
    'HTI': 'HTG',
    'HMD': 'AUD',
    'VAT': 'EUR',
    'HND': 'HNL',
    'HKG': 'HKD',
    'HUN': 'HUF',
    'ISL': 'ISK',
    'IND': 'INR',
    'IDN': 'IDR',
    'IRN': 'IRR',
    'IRQ': 'IQD',
    'IRL': 'EUR',
    'IMN': 'GBP',
    'ISR': 'ILS',
    'ITA': 'EUR',
    'JAM': 'JMD',
    'JPN': 'JPY',
    'JEY': 'GBP',
    'JOR': 'JOD',
    'KAZ': 'KZT',
    'KEN': 'KES',
    'KIR': 'AUD',
    'PRK': 'KPW',
    'KOR': 'KRW',
    'KOS': 'EUR',
    'KWT': 'KWD',
    'KGZ': 'KGS',
    'LAO': 'LAK',
    'LVA': 'EUR',
    'LBN': 'LBP',
    'LSO': 'LSL',
    'LBR': 'LRD',
    'LBY': 'LYD',
    'LIE': 'CHF',
    'LTU': 'EUR',
    'LUX': 'EUR',
    'MAC': 'MOP',
    'MKD': 'MKD',
    'MDG': 'MGA',
    'MWI': 'MWK',
    'MYS': 'MYR',
    'MDV': 'MVR',
    'MLI': 'XOF',
    'MLT': 'EUR',
    'MHL': 'USD',
    'MTQ': 'EUR',
    'MRT': 'MRU',
    'MUS': 'MUR',
    'MYT': 'EUR',
    'MEX': 'MXN',
    'FSM': 'USD',
    'MDA': 'MDL',
    'MCO': 'EUR',
    'MNG': 'MNT',
    'MNE': 'EUR',
    'MSR': 'XCD',
    'MAR': 'MAD',
    'MOZ': 'MZN',
    'MMR': 'MMK',
    'NAM': 'NAD',
    'NRU': 'AUD',
    'NPL': 'NPR',
    'NLD': 'EUR',
    'AN': 'ANG',
    'NCL': 'XPF',
    'NZL': 'NZD',
    'NIC': 'NIO',
    'NER': 'XOF',
    'NGA': 'NGN',
    'NIU': 'NZD',
    'NFK': 'AUD',
    'MNP': 'USD',
    'NOR': 'NOK',
    'OMN': 'OMR',
    'PAK': 'PKR',
    'PLW': 'USD',
    'PSE': 'ILS',
    'PAN': 'PAB',
    'PNG': 'PGK',
    'PRY': 'PYG',
    'PER': 'PEN',
    'PHL': 'PHP',
    'PCN': 'NZD',
    'POL': 'PLN',
    'PRT': 'EUR',
    'PRI': 'USD',
    'QAT': 'QAR',
    'ROU': 'RON',
    'RUS': 'RUB',
    'RWA': 'RWF',
    'REU': 'EUR',
    'BLM': 'EUR',
    'SHN': 'SHP',
    'KNA': 'XCD',
    'LCA': 'XCD',
    'MAF': 'EUR',
    'SPM': 'EUR',
    'VCT': 'XCD',
    'WSM': 'WST',
    'SMR': 'EUR',
    'STP': 'STN',
    'SAU': 'SAR',
    'SEN': 'XOF',
    'SRB': 'RSD',
    'SYC': 'SCR',
    'SLE': 'SLL',
    'SGP': 'SGD',
    'SXM': 'ANG',
    'SVK': 'EUR',
    'SVN': 'EUR',
    'SLB': 'SBD',
    'SOM': 'SOS',
    'ZAF': 'ZAR',
    'SGS': 'GBP',
    'SSD': 'SSP',
    'ESP': 'EUR',
    'LKA': 'LKR',
    'SDN': 'SDG',
    'SUR': 'SRD',
    'SJM': 'NOK',
    'SWZ': 'SZL',
    'SWE': 'SEK',
    'CHE': 'CHF',
    'SYR': 'SYP',
    'TWN': 'TWD',
    'TJK': 'TJS',
    'TZA': 'TZS',
    'THA': 'THB',
    'TLS': 'USD',
    'TGO': 'XOF',
    'TKL': 'NZD',
    'TON': 'TOP',
    'TTO': 'TTD',
    'TUN': 'TND',
    'TUR': 'TRY',
    'TKM': 'TMT',
    'TCA': 'USD',
    'TUV': 'AUD',
    'UGA': 'UGX',
    'UKR': 'UAH',
    'ARE': 'AED',
    'URY': 'UYU',
    'UMI': 'USD',
    'UZB': 'UZS',
    'VUT': 'VUV',
    'VEN': 'VES',
    'VNM': 'VND',
    'VGB': 'USD',
    'VIR': 'USD',
    'WLF': 'XPF',
    'ESH': 'MAD',
    'YEM': 'YER',
    'ZMB': 'ZMW',
    'ZWE': 'ZWG',
    'ALA': 'EUR',
  };
  Country({
    required this.isoCode,
    required this.iso3Code,
    required this.phoneCode,
    required this.name,
    required this.minLength,
    required this.maxLength,
    this.currencySymbol = '',
    this.regionCode = '',
  });

  factory Country.fromMap(Map<String, dynamic> map) {
    final iso3Code = map['iso3Code']!;
    final String currencySymbol = _getCurrencySymbolFromCode(iso3Code);

    return Country(
      name: map['name']!,
      isoCode: map['isoCode']!,
      iso3Code: iso3Code,
      currencySymbol: currencySymbol,
      phoneCode: map['phoneCode']!,
      minLength: map['minLength']!,
      maxLength: map['maxLength']!,
      regionCode: map['regionCode'] ?? '',
    );
  }
  final String name;
  final String isoCode;
  final String iso3Code;
  final String currencySymbol;
  final String phoneCode;
  final String regionCode;
  final int minLength;
  final int maxLength;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'name': name,
      'isoCode': isoCode,
      'iso3Code': iso3Code,
      'currencySymbol': currencySymbol,
      'phoneCode': phoneCode,
      'regionCode': regionCode,
      'minLength': minLength,
      'maxLength': maxLength,
    }..removeWhere((key, Object? value) => value == null);
  }

  static String _getCurrencySymbolFromCode(String? iso3Code) {
    String currencyCode = iso3ToCurrency[iso3Code] ?? iso3Code ?? '';
    if (simpleCurrencySymbols.containsKey(currencyCode)) {
      return simpleCurrencySymbols[currencyCode]!;
    }
    try {
      final NumberFormat format = NumberFormat.simpleCurrency(name: currencyCode);
      return format.currencySymbol;
    } catch (_) {
      return currencyCode;
    }
  }

  String get fullCountryCode {
    return phoneCode + regionCode;
  }

  String get displayCC {
    if (regionCode != '') {
      return '$phoneCode $regionCode';
    }
    return phoneCode;
  }
}
